FROM php:7.2.19-apache-stretch

RUN echo "deb http://deb.debian.org/debian jessie main" > /etc/apt/sources.list &&\
    echo "deb http://security.debian.org jessie/updates main" >> /etc/apt/sources.list

# install
RUN apt-get update \
    && apt-get install -y --allow-downgrades \
    	zlib1g=1:1.2.8.dfsg-2+b1 \
    	zlib1g-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        openssl libssl-dev \
        libxml2=2.9.1+dfsg1-5+deb8u7 \
        libxml2-dev \
        zip unzip \
        libzip-dev \
        git \
        vim \
        libicu-dev \
        ssmtp \
        mailutils \
    && docker-php-ext-install -j$(nproc) iconv pdo_mysql mbstring xml tokenizer zip intl \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

# apache
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/
RUN ln -s /etc/apache2/mods-available/ssl.load /etc/apache2/mods-enabled/
RUN ln -s /etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-enabled/
COPY apache/ssl/ssl-cert-snakeoil.key /etc/ssl/private/
COPY apache/ssl/ssl-cert-snakeoil.pem /etc/ssl/certs/
RUN chmod 400 /etc/ssl/private/ssl-cert-snakeoil.key \
	&& chmod 400 /etc/ssl/certs/ssl-cert-snakeoil.pem
    
# php
RUN echo 'sendmail_path = "/usr/sbin/ssmtp -t"' > /usr/local/etc/php/conf.d/mail.ini \
	&& echo "memory_limit = 256M" >> /usr/local/etc/php/php.ini \
    && echo "post_max_size = 256M" >> /usr/local/etc/php/php.ini \
    && echo "upload_max_filesize = 256M" >> /usr/local/etc/php/php.ini \
    && echo "date.timezone = Asia/Tokyo" >> /usr/local/etc/php/php.ini \
	&& yes | pecl install xdebug mcrypt-1.0.1 \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "extension=mcrypt.so" >> /usr/local/etc/php/conf.d/mcrypt.ini
    
# ssmtp
RUN echo "FromLineOverride=YES" > /etc/ssmtp/ssmtp.conf \
 	&& echo "Mailhub=bc-smtp:1025" >> /etc/ssmtp/ssmtp.conf
 	
# composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer self-update
